#!/usr/bin/env node
// Writes Config/Secrets.xcconfig (gitignored) from environment variables.
// Used by CI (GitHub repository Variables) and optionally locally.
//
//   SUPABASE_HOST              e.g. abcdefgh.supabase.co   (host only: "//" starts a comment in xcconfig files)
//   SUPABASE_PUBLISHABLE_KEY   sb_publishable_…            (safe to ship: access is enforced by RLS)
//   SUPABASE_SCHEME            https (default) | http (local stack)
//   APP_BUNDLE_ID              globally unique bundle id, e.g. io.github.<pseudo>.equipe
//
// Missing values are left out, so Base.xcconfig defaults apply and the app shows « Configuration manquante ».
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const target = path.join(root, 'Config', 'Secrets.xcconfig');

const vars = {
  SUPABASE_HOST: process.env.SUPABASE_HOST?.replace(/^https?:\/\//, '').replace(/\/+$/, ''),
  SUPABASE_PUBLISHABLE_KEY: process.env.SUPABASE_PUBLISHABLE_KEY,
  SUPABASE_SCHEME: process.env.SUPABASE_SCHEME,
  APP_BUNDLE_ID: process.env.APP_BUNDLE_ID,
};

const lines = ['// Generated by scripts/write-secrets.mjs — do not commit.'];
for (const [key, value] of Object.entries(vars)) {
  if (!value) continue;
  if (/[\r\n]/.test(value)) throw new Error(`${key} must be a single line`);
  lines.push(`${key} = ${value}`);
}
writeFileSync(target, lines.join('\n') + '\n');
const written = Object.entries(vars).filter(([, v]) => v).map(([k]) => k);
console.log(`Wrote ${path.relative(root, target)} (${written.length ? written.join(', ') : 'no values — defaults apply'})`);
