#!/usr/bin/env node
// Writes Config/Secrets.xcconfig (gitignored) from environment variables.
// Used by CI (GitHub repository Variables) and optionally locally.
//
//   SUPABASE_HOST              e.g. abcdefgh.supabase.co   (host only: "//" starts a comment in xcconfig files)
//   SUPABASE_PUBLISHABLE_KEY   sb_publishable_…            (safe to ship: access is enforced by RLS)
//   SUPABASE_SCHEME            https (default) | http (local stack)
//   APP_BUNDLE_ID              globally unique bundle id, e.g. io.github.<pseudo>.equipe
//
// Missing values are left out, so Base.xcconfig defaults apply and the app shows « Configuration manquante ».
// A secret key given as SUPABASE_PUBLISHABLE_KEY is refused: shipped in the app, it would bypass RLS for everyone.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const target = path.join(root, 'Config', 'Secrets.xcconfig');

// Host only: strips a leading http:// or https:// and anything from the first "/" (a path, a trailing slash).
const normalizeHost = (value) => value?.replace(/^https?:\/\//i, '').replace(/\/.*$/, '');

// Same rule as the app (App/Sources/Environment/SupabaseSettings.swift, isSecretKey): a secret key (sb_secret_…),
// or a legacy JWT key whose payload role is not "anon" (service_role).
function secretKeyKind(key) {
  if (key.startsWith('sb_secret_')) return 'a secret key (sb_secret_…)';
  const parts = key.split('.');
  if (parts.length !== 3) return null;
  let claims;
  try {
    claims = JSON.parse(Buffer.from(parts[1], 'base64url').toString('utf8'));
  } catch {
    return null;
  }
  if (claims === null || typeof claims !== 'object') return null;
  return claims.role === 'anon' ? null : `a JWT key whose role is ${JSON.stringify(claims.role ?? null)}, not "anon"`;
}

const vars = {
  SUPABASE_HOST: normalizeHost(process.env.SUPABASE_HOST),
  SUPABASE_PUBLISHABLE_KEY: process.env.SUPABASE_PUBLISHABLE_KEY,
  SUPABASE_SCHEME: process.env.SUPABASE_SCHEME,
  APP_BUNDLE_ID: process.env.APP_BUNDLE_ID,
};

const secretKind = vars.SUPABASE_PUBLISHABLE_KEY && secretKeyKind(vars.SUPABASE_PUBLISHABLE_KEY);
if (secretKind) {
  throw new Error(
    `SUPABASE_PUBLISHABLE_KEY is ${secretKind}. Shipped in the app, it would give everyone who extracts it ` +
      'access to every row (it bypasses RLS). Use the publishable key (sb_publishable_…) from Supabase › Project ' +
      'Settings › API Keys, and rotate the secret key if it was ever exposed.',
  );
}

const lines = ['// Generated by scripts/write-secrets.mjs — do not commit.'];
for (const [key, value] of Object.entries(vars)) {
  if (!value) continue;
  if (/[\r\n]/.test(value)) throw new Error(`${key} must be a single line`);
  lines.push(`${key} = ${value}`);
}
writeFileSync(target, lines.join('\n') + '\n');
const written = Object.entries(vars).filter(([, v]) => v).map(([k]) => k);
console.log(`Wrote ${path.relative(root, target)} (${written.length ? written.join(', ') : 'no values — defaults apply'})`);
